questions =  [

    {"id": 0, "question": "Avoidance of Trolling is the best practical way a server can prosper.", "effects": {"right": 1}},
    {"id": 1, "question": "Searching for smart, loyal members is a better way of encouraging BMC's growth then a number of shitposters.", "effects": {"right": 1}},
    {"id": 2, "question": "The Admins are always fair, as the people who run the server know best how it should be run.", "effects": {"right": 1}},
    {"id": 3, "question": "It is better to speak in #general-english then in #weeb-zone", "effects": {"right": 1}},
    {"id": 4, "question": "\"Mod abuse\" is an outdated term because the BMC mods generally make the right calls.", "effects": {"right": 1}},
    {"id": 5, "question": "A full shitpost of a server is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "BMC would be better off without @everyone pings as a joke.", "effects": {"right": 1}},
    {"id": 7, "question": "The better you are, the higher you can be found in the BMC Staff.", "effects": {"right": 1}},

    {"id": 8, "question": "Most BMC members are no-fun and should be trolled.", "effects": {"right": -1}},
    {"id": 9, "question": "A server where trolling is unpunished is an inherently good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "The current #useless-channels system should be further expanded to undermine Brazilian's monopoly.", "effects": {"right": -1}},
    {"id": 11, "question": "Punishments should not exist, ideally.", "effects": {"right": -1}},
    {"id": 12, "question": "Nothing is sacred on Discord.", "effects": {"right": -1}},
    {"id": 13, "question": "Discord moderators are fat.", "effects": {"right": -1}},
    {"id": 14, "question": "Level-based inequality is too high in the world.", "effects": {"right": -1}},

    {"id": 15, "question": "Ryan should be given server-wide powers.", "effects": {"auth": 1}},
    {"id": 16, "question": "Ryan's coups are a good thing for BMC.", "effects": {"auth": 1}},
    {"id": 17, "question": "Ryanpolls are much better then regular polls.", "effects": {"auth": 1}},
    {"id": 18, "question": "The Staff are too hard on Ryan in Rotative Elections.", "effects": {"auth": 1}},
    {"id": 19, "question": "BMC requires certain trolling-supportive Council Members in order to function.", "effects": {"auth": 1}},
    {"id": 20, "question": "The best Tally Hall song is \"&\".", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of heated gaming, trolling is more important then not being banned.", "effects": {"auth": 1}},
    {"id": 22, "question": "I hate Women.", "effects": {"auth": 1}},

    {"id": 23, "question": "Ryan should be less involved in the culture of BMC.", "effects": {"auth": -1}},
    {"id": 24, "question": "With Ryantrolls, BMC is worse-recieved.", "effects": {"auth": -1}},
    {"id": 25, "question": "The Ryan Gamer-Troll Autonomous Okrug is a good idea..", "effects": {"auth": -1}},
    {"id": 26, "question": "The quieter Ryantrolling is, the better a conversation is.", "effects": {"auth": -1}},
    {"id": 27, "question": "Ryan is the greatest troller.", "effects": {"auth": -1}},
    {"id": 28, "question": "Brazilian should have punished the Ryancoups.", "effects": {"auth": -1}},
    {"id": 29, "question": "New Members should not be exposed to Ryan's tomfoolery.", "effects": {"auth": -1}},

    {"id": 30, "question": "Two trolling individuals should be suppressed, even if they do not troll.", "effects": {"prog": 1}},
    {"id": 31, "question": "An individual's nickname should be changed if it sponsors behavior I dislike.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should follow my ideas for BMC.", "effects": {"prog": 1}},
    {"id": 33, "question": "Banning is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "I fundamentally agree with this statement:\"BMC members are like cattle that must be herded\".", "effects": {"prog": 1}},
    {"id": 35, "question": "There is only one genders (i'm secksist)", "effects": {"prog": 1}},
    {"id": 36, "question": "The creation of the RGTA Okrug didn't go far enough, in either direction.", "effects": {"prog": 1}},
    {"id": 37, "question": "After the triumph against the other three quadrants, they must be banned.", "effects": {"prog": 1}},

    {"id": 38, "question": "Banning is against my values as a server member.", "effects": {"prog": -1}},
    {"id": 39, "question": "Trollers and Untrollers are more alike then they think.", "effects": {"prog": -1}},
    {"id": 40, "question": "The RGTA Okrug should be peacefully integrated.", "effects": {"prog": -1}},
    {"id": 41, "question": "I like Moldvoa", "effects": {"prog": -1}},
    {"id": 42, "question": "Victimless rulebreaks should not be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "A server cannot be fun with schisms.", "effects": {"prog": -1}},
    {"id": 44, "question": "New Members should be encouraged to participate in BMC culture.", "effects": {"prog": -1}},
    {"id": 45, "question": "We should unban Geezo.", "effects": {"prog": -1}}
];